[server]
headless = true

[client]
showSidebarNavigation = true

[theme]
base="light"
primaryColor="#2563EB"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F9FAFB"
textColor="#111827"
font="sans serif"
