# Streamlit secrets for Supabase (replace with real values)
SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_ANON_KEY = "your-anon-key"
# Used only by sync_utils.py
SUPABASE_SERVICE_ROLE = "your-service-role-key"
